### ISSUE TITLE
onFinish - SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by virento** [vesparny/borgjs#10]
Hello, I'm attempting to use the borgjs wrapper and I'm receiving the following error when I uncomment the 'onFinish' section of the config (I filled in my own info for the mailgun service that was used in the example you provided)

root@customer-fs01:~# borgjs -c /etc/borgjs.config.js >> /var/log/borg/$(date +\%Y-\%m-\%d-\%H\%M\%S).log
/etc/borgjs.config.js:86
  onFinish: function (err, data, done) {
  ^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/borgjs/bin/index.js:77:16)

Here is a snippet of the onFinish section I'm using in the borgjs.conf.js config file (some values changed for privacy reasons):

  // the onFinish callback
  onFinish: function (err, data, done) {
    const message = err
      ? 'the backup failed'
      : `the archive ${data.archiveName} has been created`
    var execSync = require('child_process').execSync

    const command = `
        curl -s --user 'api:key-lkin3liknm456lkin345li7nlin345' \
        https://api.mailgun.net/v3/mg.example.com/messages \
        -F from='borgbackup <borgbackup@customer-fs01.example.local>' \
        -F to='Customer Support <support@example.com>' \
        -F subject='customer-fs01.example.local - borgbackup status' \
        -F text='${message}'
        `
    try {
      execSync(command)
    } catch (e) {}
    // invoke the done callback to let the process terminate properly
    done()
  }
}

Would you mind assisting me in determining why I'm receiving the error I referenced above?  I copied the entire example config which works great except for the onFinish bit.  I also tested the curl function by itself to ensure it sends the email as expected (I don't think the curl command is the issue though).

Please let me know if you need any additional information.

Any help is appreciate and thanks for creating borgjs, it's very handy.

**Comment by vesparny** [comment]
Hi,

are you maybe missing a comma before `onFinish: funct......`?

**Comment by virento** [comment]
Good call, that seems to be the problem and I've verified it now works as expected.  It looks like the example you have on the README is also missing a comma at the end of the 'prune' stanza just after the closing '}'.  I know this is commented out however for nodejs noobs like myself, it's easy to miss that in the event you uncomment the section to specify the prune options which is what I did.  Just wanted to give you a heads up in case you wanted to adjust that to avoid future inquiries like this one.

Also, had a real quick follow-up question related to the onFinish function as it's listed in the README.  As it stands in the example using mailgun to send email via my own mailgun account, should I expect to receive an email each time the backup ends regardless of the outcome or should I expect to receive an email only when there is a failure/error of some sort?

**Comment by vesparny** [comment]
@virento thanks for the head. Would you like to create a Pull Request to fix the issue on the README. Feel also free to make the documentation more understandable for people non used to JS syntax 😀

To answer your follow-up question, the `onFinish` callback is called anytime a backup process ends, regardless its result.
If a backup fails for any reason, the variable `err` will be populated.

You can use it to make accordingly a meaningful error message to use in your email (or any other medium)

```js
const message = err
      ? 'the backup failed'
      : `the archive ${data.archiveName} has been created`
``` 

please let me know if this is clear and wether you are willing to contribute to the README.

Glad you find the project useful.

cheers
