### ISSUE TITLE
borgjs support to handle lvm

### ISSUE THREAD

**Issue by unlandm** [vesparny/borgjs#4]
I'm using borgbackup for my kvm virtual machines on lvm disks. I saw borgjs. Very impressiv. Could you enhance it to handle lvm snapshots and the feature of borgbackup to handle lvm snapshots (--read-special).

Thank You,

Michael

**Comment by vesparny** [comment]
You just neet to pass the --read-special flag right?

## 

Alessandro Arnodo

On Tue, Nov 8, 2016, at 09:52 PM, unlandm wrote:

> I'm using borgbackup for my kvm virtual machines on lvm disks. I saw
> borgjs. Very impressiv. Could you enhance it to handle lvm snapshots
> and the feature of borgbackup to handle lvm snapshots (--read-
> special).
> Thank You,
> Michael
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].

Links:
1. https://github.com/vesparny/borgjs/issues/4

**Comment by unlandm** [comment]
Hi Allessandro,

please see my bashsript.

I will delete old snapshosts (perhaps from a crash), create new snapshots.

I create lvdisplay.txt to have all the information about virtual machines.

Then I call "borg create“. This part would be borgjs … to create the backup.

After deleting display.txt and snapshots.

Prune and REPOSITORY variable will be handled by borgjs in future.

Perhabs we should work on a version of borgjs which could handle creating of lvm snapshots and display.txt too.

You can read about display.txt and —read-special in the documentation of borg.

Michael

#!/bin/bash

REPOSITORY=/media/vmbackup/server1/
LVPATH=/dev/vg_vmimages/
LVNAME=`lvs --noheadings -o lv_name | tr -d '  '`

# remove old snapshots

for VM in $LVNAME;

do
    lvremove -f  /dev/vg_vmimages/$VM-snapshot
    echo „old snapshots deleted"
done

# create snapshots

for VM in $LVNAME;

do
    lvcreate --size 5120M --snapshot --name "$VM-snapshot" $LVPATH$VM
    echo „snapshots created"
done

# create lvdisplay.txt

```
lvdisplay > lvdisplay.txt
echo „lvdisplay.txt created"
```

# create borg backup

borg create -v --compress lz4 --read-special $REPOSITORY::`hostname`-`date +%Y-%m-%d` lvdisplay.txt $LVPATH*-snapshot

# remove lvdisplay.txt

rm -f lvdisplay.txt
echo „lvdisplay.txt deleted"

# remove snapshots

for VM in $LVNAME;

do
    lvremove -f  /dev/vg_vmimages/$VM-snapshot
    echo „snapshots deleted"
done

# delete all files which do not meet "keep-conditions"

borg prune -v $REPOSITORY --prefix `hostname`\- --keep-daily=7 --keep-weekly=4 --keep-monthly=3

**Comment by vesparny** [comment]
Release 2.0.0 has been shipped.
It supports custom environment variables and custom arbitrary borg options.

`npm i -g borgjs`

Please see the readme, you will have to adapt the config file.
let me know how it goes

**Comment by unlandm** [comment]
The test went ok. But I have to use my bash script, because the handling of the variables and snapshots I could't use in jscript.
But a friend of mine can use Release 2.0.0 and it works good for him.

Thanks a lot for your help. By the way. To get mail of my cronjob with a bash script I could solve with nullmailer.
