### ISSUE TITLE
Cleanup locks when Ctrl-C is invoked

### ISSUE THREAD

**Issue by lugoues** [vesparny/borgjs#6]
When you Ctrl-C borgjs leaves it's lock file around.

Note: I am running this in OS X

**Comment by vesparny** [comment]
The lock file is around, true. But it is not considered for next executions and cleanup when the system reboots.

As far as I know there is no way in node to be notified when a process is killed with Ctl + C.

Happy to investigate more if needed

**Comment by vesparny** [comment]
@Lugoues did you notice any wrong behavior due to the old lockfile being present in the tmp folder?

**Comment by lugoues** [comment]
I have not seen this as a problem any longer.  I am going to close it for now.
