### ISSUE TITLE
MaxBuffer Exceeded

### ISSUE THREAD

**Issue by lugoues** [vesparny/borgjs#7]
The --list command dumps everything to output which gives me an `An error has occurred:  Error: stderr maxBuffer exceeded` error. This occurs no matter where I dump the output.

Note: I am running this on OS X

**Comment by vesparny** [comment]
Can you please post here the config file you use?
I cannot reproduce locally.

**Comment by vesparny** [comment]
@Lugoues 

I've pushed a fix for this on master.
I will cut a new release in the next few days.

It will come with this specific fix plus a complete rework of the entire lib.

**Comment by vesparny** [comment]
@Lugoues I just shipped `borgjs@3.0.0`.
It also includes this fix.

Please note that I changed a lot the core of the library.
You will need to readapt the configuration file.

Take a look at the README and at the CHANGELOG.
