### ISSUE TITLE
Support Tilde Expansion

### ISSUE THREAD

**Issue by lugoues** [vesparny/borgjs#8]
When ~ is used in an file path options (path, excludes, options)

**Comment by vesparny** [comment]
Can you please post here the config file you use?
I cannot reproduce locally.

**Comment by lugoues** [comment]
Sorry for the late reply.
```
$/usr/local/bin/borgjs --config ~/.config/borg/borgjs.config
An error has occurred:  Error: No valid paths found in the "paths" option.
```
path block in the config looks like 
```  
paths: [
    '~'
  ],
```

**Comment by vesparny** [comment]
I see.

The node `path` module does not expand `tilde` by default.
Even though we could introduce some lib for managing this specific case (https://github.com/sindresorhus/untildify), I'd say it makes more sense to keep things simple and always use full paths in the configuration file.

I am open to accept PR to clarify this in the readme.

Thanks
